name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'
          - '3.1.4'
        rails:
          - '7.1'
          - '7.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Run "bundle install"
      run: bundle install
    - name: Run standard
      run: bundle exec rake standard
    - name: Run unit tests
      run: bundle exec rake test
    - name: Run integration tests
      env:
        RAILS_VERSION: ${{ matrix.rails }}
      run: ruby test/railsfile.rb
